const jsonData = [
    {
        "action": "Violations were cited in the following area(s).",
        "boro": "BRONX",
        "building": "228",
        "camis": "50005347",
        "critical_flag": "Critical",
        "cuisine_description": "American",
        "dba": "COLD CUT CITY BUNNY DELI 2",
        "grade": "B",
        "grade_date": "2016-01-25T00:00:00.000",
        "inspection_date": "2016-01-25T00:00:00.000",
        "inspection_type": "Cycle Inspection / Re-inspection",
        "phone": "7185432533",
        "record_date": "2018-03-19T06:00:54.000",
        "score": "20",
        "street": "W 231ST ST",
        "violation_code": "04K",
        "violation_description": "Evidence of rats or live rats present in facility's food and/or non-food areas.",
        "zipcode": "10463"
    },
    {
        "action": "Violations were cited in the following area(s).",
        "boro": "QUEENS",
        "building": "3737",
        "camis": "40366543",
        "critical_flag": "Critical",
        "cuisine_description": "Chinese",
        "dba": "JARDIN DE CHINA REST",
        "grade": "A",
        "grade_date": "2015-10-20T00:00:00.000",
        "inspection_date": "2015-10-20T00:00:00.000",
        "inspection_type": "Cycle Inspection / Re-inspection",
        "phone": "7184763755",
        "record_date": "2018-03-19T06:00:54.000",
        "score": "12",
        "street": "JUNCTION BOULEVARD",
        "violation_code": "06A",
        "violation_description": "Personal cleanliness inadequate. Outer garment soiled with possible contaminant.  Effective hair restraint not worn in an area where food is prepared.",
        "zipcode": "11368"
    },
    {
        "action": "Establishment Closed by DOHMH.  Violations were cited in the following area(s) and those requiring immediate action were addressed.",
        "boro": "BROOKLYN",
        "building": "837",
        "camis": "41352974",
        "critical_flag": "Not Critical",
        "cuisine_description": "Japanese",
        "dba": "SAKURA 6 JAPANESE CUISINE",
        "inspection_date": "2015-10-14T00:00:00.000",
        "inspection_type": "Cycle Inspection / Re-inspection",
        "phone": "7183497888",
        "record_date": "2018-03-19T06:00:54.000",
        "score": "48",
        "street": "MANHATTAN AVENUE",
        "violation_code": "08A",
        "violation_description": "Facility not vermin proof. Harborage or conditions conducive to attracting vermin to the premises and/or allowing vermin to exist.",
        "zipcode": "11222"
    },
    {
        "action": "Violations were cited in the following area(s).",
        "boro": "QUEENS",
        "building": "15624",
        "camis": "41476602",
        "critical_flag": "Not Critical",
        "cuisine_description": "Bakery",
        "dba": "PARIS BAGUETTE",
        "grade": "A",
        "grade_date": "2015-11-02T00:00:00.000",
        "inspection_date": "2015-11-02T00:00:00.000",
        "inspection_type": "Cycle Inspection / Initial Inspection",
        "phone": "7189610404",
        "record_date": "2018-03-19T06:00:54.000",
        "score": "12",
        "street": "NORTHERN BOULEVARD",
        "violation_code": "10F",
        "violation_description": "Non-food contact surface improperly constructed. Unacceptable material used. Non-food contact surface or equipment improperly maintained and/or not properly sealed, raised, spaced or movable to allow accessibility for cleaning on all sides, above and underneath the unit.",
        "zipcode": "11354"
    },
    {
        "action": "Violations were cited in the following area(s).",
        "boro": "QUEENS",
        "building": "4437",
        "camis": "41502640",
        "critical_flag": "Not Critical",
        "cuisine_description": "Sandwiches/Salads/Mixed Buffet",
        "dba": "SMALL KITCHEN",
        "inspection_date": "2016-08-12T00:00:00.000",
        "inspection_type": "Cycle Inspection / Initial Inspection",
        "phone": "7186066200",
        "record_date": "2018-03-19T06:00:54.000",
        "score": "13",
        "street": "VERNON BOULEVARD",
        "violation_code": "08C",
        "violation_description": "Pesticide use not in accordance with label or applicable laws. Prohibited chemical used/stored. Open bait station used.",
        "zipcode": "11101"
    },
    {
        "action": "Violations were cited in the following area(s).",
        "boro": "QUEENS",
        "building": "2310",
        "camis": "50037637",
        "critical_flag": "Critical",
        "cuisine_description": "Vietnamese/Cambodian/Malaysia",
        "dba": "BIA RESTAURANT & BAR",
        "grade": "A",
        "grade_date": "2017-04-10T00:00:00.000",
        "inspection_date": "2017-04-10T00:00:00.000",
        "inspection_type": "Cycle Inspection / Re-inspection",
        "phone": "7187520797",
        "record_date": "2018-03-19T06:00:54.000",
        "score": "13",
        "street": "JACKSON AVE",
        "violation_code": "04M",
        "violation_description": "Live roaches present in facility's food and/or non-food areas.",
        "zipcode": "11101"
    },
    {
        "action": "Violations were cited in the following area(s).",
        "boro": "STATEN ISLAND",
        "building": "170",
        "camis": "41443150",
        "critical_flag": "Critical",
        "cuisine_description": "Pizza/Italian",
        "dba": "VILLA MONTE II PIZZERIA AND RESTAURANT",
        "grade": "A",
        "grade_date": "2015-01-13T00:00:00.000",
        "inspection_date": "2015-01-13T00:00:00.000",
        "inspection_type": "Cycle Inspection / Re-inspection",
        "phone": "7186680490",
        "record_date": "2018-03-19T06:00:54.000",
        "score": "12",
        "street": "NEW DORP LANE",
        "violation_code": "06D",
        "violation_description": "Food contact surface not properly washed, rinsed and sanitized after each use and following any activity when contamination may have occurred.",
        "zipcode": "10306"
    },
    {
        "action": "Violations were cited in the following area(s).",
        "boro": "MANHATTAN",
        "building": "205",
        "camis": "41681758",
        "critical_flag": "Not Critical",
        "cuisine_description": "American",
        "dba": "CAFE FRESCO",
        "grade": "A",
        "grade_date": "2016-12-07T00:00:00.000",
        "inspection_date": "2016-12-07T00:00:00.000",
        "inspection_type": "Cycle Inspection / Initial Inspection",
        "phone": "2123555151",
        "record_date": "2018-03-19T06:00:54.000",
        "score": "10",
        "street": "EAST   60 STREET",
        "violation_code": "10B",
        "violation_description": "Plumbing not properly installed or maintained; anti-siphonage or backflow prevention device not provided where required; equipment or floor not properly drained; sewage disposal system in disrepair or not functioning properly.",
        "zipcode": "10022"
    }
]